# Generated by Django 6.0.3 on 2026-03-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_categoriamodel_productomodel_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedormodel',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='clientemodel',
            name='direccion',
        ),
        migrations.AddField(
            model_name='clientemodel',
            name='calle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientemodel',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientemodel',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clientemodel',
            name='colonia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientemodel',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proveedormodel',
            name='calle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proveedormodel',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedormodel',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='proveedormodel',
            name='colonia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ClienteTelefonoModel',
        ),
        migrations.DeleteModel(
            name='TelefonoModel',
        ),
        migrations.DeleteModel(
            name='DireccionModel',
        ),
    ]
